<?php

use Illuminate\Database\Seeder;

class list_countries extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $iso = [ 
          '',  
         'AF',
         'AX',
         'AL',
         'DE',
         'AD',
         'AO',
         'AI',
         'AQ',
         'AG',
         'AN',
         'SA',
         'DZ',
         'AR',
         'AM',
         'AW',
         'AU',
         'AT',
         'AZ',
         'BS',
         'BH',
         'BD',
         'BB',
         'BY',
         'BE',
         'BZ',
         'BJ',
         'BM',
         'BT',
         'BO',
         'BA',
         'BW',
         'BV',
         'BR',
         'BN',
         'BG',
         'BF',
         'BI',
         'CV',
         'KY',
         'KH',
         'CM',
         'CA',
         'CF',
         'TD',
         'CZ',
         'CL',
         'CN',
         'CY',
         'CX',
         'VA',
         'CC',
         'CO',
         'KM',
         'CD',
         'CG',
         'CK',
         'KP',
         'KR',
         'CI',
         'CR',
         'HR',
         'CU',
         'DK',
         'DM',
         'DO',
         'EC',
         'EG',
         'SV',
         'AE',
         'ER',
         'SK',
         'SI',
         'ES',
         'UM',
         'US',
         'EE',
         'ET',
         'FO',
         'PH',
         'FI',
         'FJ',
         'FR',
         'GA',
         'GM',
         'GE',
         'GS',
         'GH',
         'GI',
         'GD',
         'GR',
         'GL',
         'GP',
         'GU',
         'GT',
         'GF',
         'GN',
         'GQ',
         'GW',
         'GY',
         'HT',
         'HM',
         'HN',
         'HK',
         'HU',
         'IN',
         'ID',
         'IR',
         'IQ',
         'IE',
         'IS',
         'IL',
         'IT',
         'JM',
         'JP',
         'JO',
         'KZ',
         'KE',
         'KG',
         'KI',
         'KW',
         'LA',
         'LS',
         'LV',
         'LB',
         'LR',
         'LY',
         'LI',
         'LT',
         'LU',
         'MO',
         'MK',
         'MG',
         'MY',
         'MW',
         'MV',
         'ML',
         'MT',
         'FK',
         'MP',
         'MA',
         'MH',
         'MQ',
         'MU',
         'MR',
         'YT',
         'MX',
         'FM',
         'MD',
         'MC',
         'MN',
         'MS',
         'MZ',
         'MM',
         'NA',
         'NR',
         'NP',
         'NI',
         'NE',
         'NG',
         'NU',
         'NF',
         'NO',
         'NC',
         'NZ',
         'OM',
         'NL',
         'PK',
         'PW',
         'PS',
         'PA',
         'PG',
         'PY',
         'PE',
         'PN',
         'PF',
         'PL',
         'PT',
         'PR',
         'QA',
         'GB',
         'RE',
         'RW',
         'RO',
         'RU',
         'EH',
         'SB',
         'WS',
         'AS',
         'KN',
         'SM',
         'PM',
         'VC',
         'SH',
         'LC',
         'ST',
         'SN',
         'CS',
         'SC',
         'SL',
         'SG',
         'SY',
         'SO',
         'LK',
         'SZ',
         'ZA',
         'SD',
         'SE',
         'CH',
         'SR',
         'SJ',
         'TH',
         'TW',
         'TZ',
         'TJ',
         'IO',
         'TF',
         'TL',
         'TG',
         'TK',
         'TO',
         'TT',
         'TN',
         'TC',
         'TM',
         'TR',
         'TV',
         'UA',
         'UG',
         'UY',
         'UZ',
         'VU',
         'VE',
         'VN',
         'VG',
         'VI',
         'WF',
         'YE',
         'DJ',
         'ZM',
         'ZW',
        

        ];

        $countries = [
            'País de Residencia',
            'Afganistán',
            'Islas Gland',
            'Albania',
            'Alemania',
            'Andorra',
            'Angola',
            'Anguilla',
            'Antártida',
            'Antigua y Barbuda',
            'Antillas Holandesas',
            'Arabia Saudí',
            'Argelia',
            'Argentina',
            'Armenia',
            'Aruba',
            'Australia',
            'Austria',
            'Azerbaiyán',
            'Bahamas',
            'Bahréin',
            'Bangladesh',
            'Barbados',
            'Bielorrusia',
            'Bélgica',
            'Belice',
            'Benin',
            'Bermudas',
            'Bhután',
            'Bolivia',
            'Bosnia y Herzegovina',
            'Botsuana',
            'Isla Bouvet',
            'Brasil',
            'Brunéi',
            'Bulgaria',
            'Burkina Faso',
            'Burundi',
            'Cabo Verde',
            'Islas Caimán',
            'Camboya',
            'Camerún',
            'Canadá',
            'República Centroafricana',
            'Chad',
            'República Checa',
            'Chile',
            'China',
            'Chipre',
            'Isla de Navidad',
            'Ciudad del Vaticano',
            'Islas Cocos',
            'Colombia',
            'Comoras',
            'República Democrática del Congo',
            'Congo',
            'Islas Cook',
            'Corea del Norte',
            'Corea del Sur',
            'Costa de Marfil',
            'Costa Rica',
            'Croacia',
            'Cuba',
            'Dinamarca',
            'Dominica',
            'República Dominicana',
            'Ecuador',
            'Egipto',
            'El Salvador',
            'Emiratos Árabes Unidos',
            'Eritrea',
            'Eslovaquia',
            'Eslovenia',
            'España',
            'Islas ultramarinas de Estados Unidos',
            'Estados Unidos',
            'Estonia',
            'Etiopía',
            'Islas Feroe',
            'Filipinas',
            'Finlandia',
            'Fiyi',
            'Francia',
            'Gabón',
            'Gambia',
            'Georgia',
            'Islas Georgias del Sur y Sandwich del Sur',
            'Ghana',
            'Gibraltar',
            'Granada',
            'Grecia',
            'Groenlandia',
            'Guadalupe',
            'Guam',
            'Guatemala',
            'Guayana Francesa',
            'Guinea',
            'Guinea Ecuatorial',
            'Guinea-Bissau',
            'Guyana',
            'Haití',
            'Islas Heard y McDonald',
            'Honduras',
            'Hong Kong',
            'Hungría',
            'India',
            'Indonesia',
            'Irán',
            'Iraq',
            'Irlanda',
            'Islandia',
            'Israel',
            'Italia',
            'Jamaica',
            'Japón',
            'Jordania',
            'Kazajstán',
            'Kenia',
            'Kirguistán',
            'Kiribati',
            'Kuwait',
            'Laos',
            'Lesotho',
            'Letonia',
            'Líbano',
            'Liberia',
            'Libia',
            'Liechtenstein',
            'Lituania',
            'Luxemburgo',
            'Macao',
            'ARY Macedonia',
            'Madagascar',
            'Malasia',
            'Malawi',
            'Maldivas',
            'Malí',
            'Malta',
            'Islas Malvinas',
            'Islas Marianas del Norte',
            'Marruecos',
            'Islas Marshall',
            'Martinica',
            'Mauricio',
            'Mauritania',
            'Mayotte',
            'México',
            'Micronesia',
            'Moldavia',
            'Mónaco',
            'Mongolia',
            'Montserrat',
            'Mozambique',
            'Myanmar',
            'Namibia',
            'Nauru',
            'Nepal',
            'Nicaragua',
            'Níger',
            'Nigeria',
            'Niue',
            'Isla Norfolk',
            'Noruega',
            'Nueva Caledonia',
            'Nueva Zelanda',
            'Omán',
            'Países Bajos',
            'Pakistán',
            'Palau',
            'Palestina',
            'Panamá',
            'Papúa Nueva Guinea',
            'Paraguay',
            'Perú',
            'Islas Pitcairn',
            'Polinesia Francesa',
            'Polonia',
            'Portugal',
            'Puerto Rico',
            'Qatar',
            'Reino Unido',
            'Reunión',
            'Ruanda',
            'Rumania',
            'Rusia',
            'Sahara Occidental',
            'Islas Salomón',
            'Samoa',
            'Samoa Americana',
            'San Cristóbal y Nevis',
            'San Marino',
            'San Pedro y Miquelón',
            'San Vicente y las Granadinas',
            'Santa Helena',
            'Santa Lucía',
            'Santo Tomé y Príncipe',
            'Senegal',
            'Serbia y Montenegro',
            'Seychelles',
            'Sierra Leona',
            'Singapur',
            'Siria',
            'Somalia',
            'Sri Lanka',
            'Suazilandia',
            'Sudáfrica',
            'Sudán',
            'Suecia',
            'Suiza',
            'Surinam',
            'Svalbard y Jan Mayen',
            'Tailandia',
            'Taiwán',
            'Tanzania',
            'Tayikistán',
            'Territorio Británico del Océano Índico',
            'Territorios Australes Franceses',
            'Timor Oriental',
            'Togo',
            'Tokelau',
            'Tonga',
            'Trinidad y Tobago',
            'Túnez',
            'Islas Turcas y Caicos',
            'Turkmenistán',
            'Turquía',
            'Tuvalu',
            'Ucrania',
            'Uganda',
            'Uruguay',
            'Uzbekistán',
            'Vanuatu',
            'Venezuela',
            'Vietnam',
            'Islas Vírgenes Británicas',
            'Islas Vírgenes de los Estados Unidos',
            'Wallis y Futuna',
            'Yemen',
            'Yibuti',
            'Zambia',
            'Zimbabue',
           

        ];

        DB::table('countries')->truncate();
        
        for ($i=0; $i < 241; $i++) {
            \DB::table('countries')->insert(array(
                   'iso' => $iso[$i],
                   'name'  => $countries[$i],
                   'created_at' => date('Y-m-d H:m:s'),
                   'updated_at' => date('Y-m-d H:m:s')
            ));
        }
    }
}